---
- name: inetrouter | Config network
  hosts: R1
  become: true
  vars:
    id: '1'
    hostname: 'R1'
    cost: '1000'
    ospf:
      - network: '10.10.10.0/30' 
        area: '0'
      - network: '10.10.10.4/30' 
        area: '0'
      - network: '10.10.10.12/30' 
        area: '0'

  tasks:

    - name: install quagga
      yum: 
        name: quagga
        state: latest 

    - name: R1 | Forwarding enable  
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: R1 | Default filter desable 
      sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: '0'
        sysctl_set: yes    

    - name: R1 | All interfaces filter desable
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        sysctl_set: yes

    - name: R1 | All interfaces filter desable
      sysctl:
        name: net.ipv4.conf.eth1.rp_filter
        value: '0'
        sysctl_set: yes                    

    - name: R1 | All interfaces filter desable
      sysctl:
        name: net.ipv4.conf.eth2.rp_filter
        value: '0'
        sysctl_set: yes

    - name: R1 | All interfaces filter desable
      sysctl:
        name: net.ipv4.conf.eth3.rp_filter
        value: '0'
        sysctl_set: yes        

    - name: R1 | copy config file quagga
      template:
        src: zebra.conf.j2
        dest: /etc/quagga/zebra.conf
   
    - name: R1 | copy config file quagga
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf

    - name: restart network
      systemd:
        name: zebra
        state: started
        enabled: yes

    - name: restart network
      systemd:
        name: ospfd
        state: started
        enabled: yes

- name: R2 | Config OSPF
  hosts: R2
  become: true
  vars:
    id: '2'
    hostname: 'R2'
    cost: '1000'
    ospf:
      - network: '10.10.10.0/30' 
        area: '0'
      - network: '10.10.10.8/30' 
        area: '0'

  tasks:

    - name: install quagga
      yum: 
        name: quagga
        state: latest 

    - name: R2 | Forwarding enable  
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: R2 | Default filter desable
      sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: '0'
        sysctl_set: yes    

    - name: R2 | All interfaces filter desable
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        sysctl_set: yes 

    - name: R2 | eth1 filter desable
      sysctl:
        name: net.ipv4.conf.eth1.rp_filter
        value: '0'
        sysctl_set: yes                    

    - name: R2 | eth2 filter desable
      sysctl:
        name: net.ipv4.conf.eth2.rp_filter
        value: '0'
        sysctl_set: yes                     

    - name: R2 | copy config file quagga
      template:
        src: zebra.conf.j2
        dest: /etc/quagga/zebra.conf
   
    - name: R2 | copy config file quagga
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf

    - name: restart zebra
      systemd:
        name: zebra
        state: started
        enabled: yes

    - name: restart ospfd
      systemd:
        name: ospfd
        state: started
        enabled: yes

- name: R3 | Config OSPF
  hosts: R3
  become: true
  vars:
    id: '3'
    hostname: 'R3'
    ospf:
      - network: '10.10.10.4/30' 
        area: '0'
      - network: '10.10.10.8/30' 
        area: '0'
      - network: '10.10.10.16/30' 
        area: '0'        

  tasks:

    - name: install quagga
      yum: 
        name: quagga
        state: latest 

    - name: R3 | Forwarding enable  
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: R3 | Default filter desable
      sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: '0'
        sysctl_set: yes    

    - name: R3 | All interfaces filter desable
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        sysctl_set: yes              

    - name: R3 | copy config file quagga
      template:
        src: zebra.conf.j2
        dest: /etc/quagga/zebra.conf
   
    - name: R3| copy config file quagga
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf

    - name: restart zebra
      systemd:
        name: zebra
        state: started
        enabled: yes

    - name: restart ospfd
      systemd:
        name: ospfd
        state: started
        enabled: yes     

- name: R4 | Config OSPF
  hosts: R4
  become: true
  vars:
    id: '4'
    hostname: 'R4'
    ospf:
      - network: '10.10.10.12/30' 
        area: '0'
      - network: '10.10.10.16/30' 
        area: '0'

  tasks:

    - name: install quagga
      yum: 
        name: quagga
        state: latest 

    - name: R4 | Forwarding enable  
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: R4 | Default filter desable
      sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: '0'
        sysctl_set: yes    

    - name: R4 | All interfaces filter desable
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        sysctl_set: yes              

    - name: R4 | copy config file quagga
      template:
        src: zebra.conf.j2
        dest: /etc/quagga/zebra.conf
   
    - name: R4 | copy config file quagga
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf

    - name: restart zebra
      systemd:
        name: zebra
        state: started
        enabled: yes

    - name: restart ospfd
      systemd:
        name: ospfd
        state: started
        enabled: yes           